// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz_hbtLrlxyPs2GW_R1lLkoN1xqcuqB18',
    appId: '1:464048890925:web:9f21fd414ba88f401484a4',
    messagingSenderId: '464048890925',
    projectId: 'consultancy-e70bb',
    authDomain: 'consultancy-e70bb.firebaseapp.com',
    storageBucket: 'consultancy-e70bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3FVcjFuGkpaL3kunYCvGlOw_jxQzeECI',
    appId: '1:464048890925:android:be43d78eed226f081484a4',
    messagingSenderId: '464048890925',
    projectId: 'consultancy-e70bb',
    storageBucket: 'consultancy-e70bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpTnoqo9uNhQQf4W4Gs12CYIi6GrbkOf0',
    appId: '1:464048890925:ios:52846598ce6ee1241484a4',
    messagingSenderId: '464048890925',
    projectId: 'consultancy-e70bb',
    storageBucket: 'consultancy-e70bb.firebasestorage.app',
    iosBundleId: 'com.example.sampleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpTnoqo9uNhQQf4W4Gs12CYIi6GrbkOf0',
    appId: '1:464048890925:ios:52846598ce6ee1241484a4',
    messagingSenderId: '464048890925',
    projectId: 'consultancy-e70bb',
    storageBucket: 'consultancy-e70bb.firebasestorage.app',
    iosBundleId: 'com.example.sampleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz_hbtLrlxyPs2GW_R1lLkoN1xqcuqB18',
    appId: '1:464048890925:web:c961e7be891c90261484a4',
    messagingSenderId: '464048890925',
    projectId: 'consultancy-e70bb',
    authDomain: 'consultancy-e70bb.firebaseapp.com',
    storageBucket: 'consultancy-e70bb.firebasestorage.app',
  );
}
